name: CI (Packer + IaC Security)

on:
  push:
    branches: [main, develop]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, develop]

jobs:
  ci:
    runs-on: [self-hosted, Linux, X64, org-build, org-deploy]  # EXACT runner labels

    steps:
      - name: Checkout
        uses: https://data.forgejo.org/actions/checkout@v4
        with:
          persist-credentials: false

      - name: Prepare tools (packer, python/pip, curl, unzip)
        run: |
          set -euo pipefail
          apt-get update -y
          apt-get install -y --no-install-recommends ca-certificates curl unzip python3 python3-pip git

          PACKER_VERSION="$(curl -fsSL https://checkpoint-api.hashicorp.com/v1/check/packer | \
            python3 -c 'import sys, json; print(json.load(sys.stdin)["current_version"])')"
          curl -fsSLo /tmp/packer.zip "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip"
          unzip -o /tmp/packer.zip -d /usr/local/bin
          packer version

          pip3 install --no-cache-dir checkov
          curl -fsSLo /usr/local/bin/tfsec "https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-linux-amd64"
          chmod +x /usr/local/bin/tfsec

      - name: Packer fmt check
        run: |
          mkdir -p ci-logs
          packer fmt -check -recursive . 2>&1 | tee ci-logs/packer-fmt.log

      - name: Packer validate
        run: |
          mkdir -p ci-logs
          mapfile -t PKR_HCL < <(find . -type f -name "*.pkr.hcl")
          mapfile -t PKR_JSON < <(find . -type f -name "*.json")

          if [ "\${#PKR_HCL[@]}" -eq 0 ] && [ "\${#PKR_JSON[@]}" -eq 0 ]; then
            echo "No packer templates found."
            exit 0
          fi

          for f in "\${PKR_HCL[@]}"; do
            packer validate "\$f"
          done

          for f in "\${PKR_JSON[@]}"; do
            packer validate "\$f"
          done 2>&1 | tee ci-logs/packer-validate.log

      - name: Detect Terraform
        id: detect_tf
        run: |
          if find . -type f -name "*.tf" -o -name "*.tfvars" | grep -q .; then
            echo "has_tf=true" >> $GITHUB_OUTPUT
          else
            echo "has_tf=false" >> $GITHUB_OUTPUT
          fi

      - name: Checkov Scan
        if: ${{ steps.detect_tf.outputs.has_tf == 'true' }}
        run: |
          mkdir -p ci-logs
          checkov -d . 2>&1 | tee ci-logs/checkov.log

      - name: tfsec Scan
        if: ${{ steps.detect_tf.outputs.has_tf == 'true' }}
        run: |
          mkdir -p ci-logs
          tfsec . 2>&1 | tee ci-logs/tfsec.log

      - name: Upload CI logs
        if: ${{ always() }}
        uses: https://data.forgejo.org/actions/upload-artifact@v4
        with:
          name: ci-logs
          path: ci-logs
